token:
  expiration_time: 864000000 
  secret: '{cipher}AYBKCz+k3MXsySynwCqjZVOJrd2kv6WC//Uh2Hb7bffeUWrJOSjmEIf02RAlIqMDeAOMfIWEZwDaXR1/yaV91FgOvrSxCbazfJVznSIXPiK5vdpEVPWXsA+442lou1UkFF1vEAgC2gjX+wuRziC+PI8cL9dOlxqyH9fyEmoHrTx9GulBq079jUrk25e007EkPWYeMUHoE16HbvhyaqdjoWT1LrV4gnaDOkIAM7WtOB5xMKfFORzFME/id2OT2ZtS3237EHmI+oBC0M7UkNnVe2WjEsBoJdlErjjnG1kj+qp/1WZMT/u1PROUyV111wprB6qw1gvy27bKglxHr6kUqEgNR+1ZhdAvt0R/ezDSy76fWpvNnE0n6fudcTvdP5SK0Gb0hAReGFKSBSG8tfOI6FBXZgVaB0V+tyEtqin8/ZSMgsWdA1JjK45TS1+MKGzgTXqumiNOr0f4JK/yciZivGqz7jDW1RhZc3D66ITGuOqlyZjkIjE+kePEqlalLiokEdTFr2VFxN7GS+F4h6CjnsTplShNWkz/SPJKkYSUa2ySw4Lf3XgsMQY8PIMVC3aN04gtH8VHQgw0KTk4EgFEHr/opaFPgJVQJnJWDxmFwApr30OyYRhK4lvkLCEdLkypRy0='

gateway:
  ip: 172.18.0.1
